// <auto-generated />
using System;
using Data_Access_Layer.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Access_Layer.Migrations
{
    [DbContext(typeof(SkincareManagementContext))]
    [Migration("20250325065832_AddProductIdFeedBack")]
    partial class AddProductIdFeedBack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data_Access_Layer.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("accountId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__F267251E4DAEF09E");

                    b.HasIndex(new[] { "RoleId" }, "IX_Account_roleId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cartId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountId");

                    b.HasKey("CartId")
                        .HasName("PK__Cart__415B03B8F725E603");

                    b.HasIndex(new[] { "AccountId" }, "IX_Cart_accountId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cartItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("cartId");

                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("CartItemId")
                        .HasName("PK__Cart_Ite__283983B6220EF485");

                    b.HasIndex(new[] { "CartId" }, "IX_Cart_Item_cartId");

                    b.HasIndex(new[] { "ProductId" }, "IX_Cart_Item_productId");

                    b.ToTable("Cart_Item", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("categoryId");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("categoryName");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__23CAF1D80D045828");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountId");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullName");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phone");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__B611CB7DA35A0B5D");

                    b.HasIndex(new[] { "AccountId" }, "IX_Customer_accountId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountId");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullName");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("position");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__C134C9C1F2DDE5B8");

                    b.HasIndex(new[] { "AccountId" }, "IX_Employee_accountId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedbackId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductId1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__2613FD24B05CC7C6");

                    b.HasIndex("ProductId1");

                    b.HasIndex(new[] { "AccountId" }, "IX_Feedback_accountId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("imageId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imageUrl");

                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productId");

                    b.HasKey("ImageId")
                        .HasName("PK__Image__336E9B559269C996");

                    b.HasIndex(new[] { "ProductId" }, "IX_Image_productId");

                    b.ToTable("Image", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("newsId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employeeId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("NewsId")
                        .HasName("PK__News__5218041E4AAEFF92");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_News_employeeId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountId");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("orderDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__0809335D65E1E68A");

                    b.HasIndex(new[] { "AccountId" }, "IX_Order_accountId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderDetailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productId");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__Order_De__E4FEDE4A234C9FC4");

                    b.HasIndex(new[] { "OrderId" }, "IX_Order_Detail_orderId");

                    b.HasIndex(new[] { "ProductId" }, "IX_Order_Detail_productId");

                    b.ToTable("Order_Detail", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.OrderPromotion", b =>
                {
                    b.Property<int>("OrderPromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderPromotionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderPromotionId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotionId");

                    b.HasKey("OrderPromotionId")
                        .HasName("PK__Order_Pr__69F6C47326D5E729");

                    b.HasIndex(new[] { "OrderId" }, "IX_Order_Promotion_orderId");

                    b.HasIndex(new[] { "PromotionId" }, "IX_Order_Promotion_promotionId");

                    b.ToTable("Order_Promotion", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("paymentDate");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("paymentMethod");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__A0D9EFC67F613395");

                    b.HasIndex(new[] { "OrderId" }, "IX_Payment_orderId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Point", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pointId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("accountId");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.HasKey("PointId")
                        .HasName("PK__Point__4CB435AEA4B2E229");

                    b.HasIndex(new[] { "AccountId" }, "IX_Point_accountId");

                    b.ToTable("Point", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productId");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("categoryId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.HasKey("ProductId")
                        .HasName("PK__Product__2D10D16A8537E9D8");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Product_categoryId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.ProductPromotion", b =>
                {
                    b.Property<int>("ProductPromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productPromotionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductPromotionId"));

                    b.Property<string>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("productId");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotionId");

                    b.HasKey("ProductPromotionId")
                        .HasName("PK__Product___3F1B3D11EDCBEC9A");

                    b.HasIndex(new[] { "ProductId" }, "IX_Product_Promotion_productId");

                    b.HasIndex(new[] { "PromotionId" }, "IX_Product_Promotion_promotionId");

                    b.ToTable("Product_Promotion", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promotionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("discount");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("endDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("startDate");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__99EB696E792C7FF3");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.PromotionDetail", b =>
                {
                    b.Property<int>("PromotionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promotionDetailId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionDetailId"));

                    b.Property<string>("DetailDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detailDescription");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotionId");

                    b.HasKey("PromotionDetailId")
                        .HasName("PK__Promotio__74CA3CF1D2EEDDBF");

                    b.HasIndex(new[] { "PromotionId" }, "IX_Promotion_Detail_promotionId");

                    b.ToTable("Promotion_Detail", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("roleName");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__CD98462A4B269C18");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Account", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Account__roleId__4BAC3F29");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Cart", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Account", "Account")
                        .WithMany("Carts")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Cart__accountId__619B8048");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.CartItem", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .HasConstraintName("FK__Cart_Item__cartI__6477ECF3");

                    b.HasOne("Data_Access_Layer.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Cart_Item__produ__656C112C");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Customer", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Account", "Account")
                        .WithMany("Customers")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Customer__accoun__4E88ABD4");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Employee", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Account", "Account")
                        .WithMany("Employees")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Employee__accoun__5165187F");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Feedback", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Account", "Account")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Feedback__accoun__6EF57B66");

                    b.HasOne("Data_Access_Layer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId1");

                    b.Navigation("Account");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Image", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Image__productId__5EBF139D");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.News", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Employee", "Employee")
                        .WithMany("News")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK__News__employeeId__5441852A");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Order", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Order__accountId__68487DD7");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.OrderDetail", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Order_Det__order__6B24EA82");

                    b.HasOne("Data_Access_Layer.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Order_Det__produ__6C190EBB");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.OrderPromotion", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Order", "Order")
                        .WithMany("OrderPromotions")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Order_Pro__order__7B5B524B");

                    b.HasOne("Data_Access_Layer.Entities.Promotion", "Promotion")
                        .WithMany("OrderPromotions")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK__Order_Pro__promo__7C4F7684");

                    b.Navigation("Order");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Payment", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Payment__orderId__7F2BE32F");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Point", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Account", "Account")
                        .WithMany("Points")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Point__accountId__571DF1D5");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Product", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Product__categor__5BE2A6F2");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.ProductPromotion", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Product", "Product")
                        .WithMany("ProductPromotions")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Product_P__produ__778AC167");

                    b.HasOne("Data_Access_Layer.Entities.Promotion", "Promotion")
                        .WithMany("ProductPromotions")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK__Product_P__promo__787EE5A0");

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.PromotionDetail", b =>
                {
                    b.HasOne("Data_Access_Layer.Entities.Promotion", "Promotion")
                        .WithMany("PromotionDetails")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK__Promotion__promo__74AE54BC");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Account", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Customers");

                    b.Navigation("Employees");

                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Employee", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderPromotions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Images");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductPromotions");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Promotion", b =>
                {
                    b.Navigation("OrderPromotions");

                    b.Navigation("ProductPromotions");

                    b.Navigation("PromotionDetails");
                });

            modelBuilder.Entity("Data_Access_Layer.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
